// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cortexapps/axon-go/.generated/proto/github.com/cortexapps/axon (interfaces: CortexApiClient,AxonAgentClient)
//
// Generated by this command:
//
//	mockgen github.com/cortexapps/axon-go/.generated/proto/github.com/cortexapps/axon CortexApiClient,AxonAgentClient
//

// Package mock_axon is a generated GoMock package.
package mock_axon

import (
	context "context"
	reflect "reflect"

	axon "github.com/cortexapps/axon-go/.generated/proto/github.com/cortexapps/axon"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockCortexApiClient is a mock of CortexApiClient interface.
type MockCortexApiClient struct {
	ctrl     *gomock.Controller
	recorder *MockCortexApiClientMockRecorder
	isgomock struct{}
}

// MockCortexApiClientMockRecorder is the mock recorder for MockCortexApiClient.
type MockCortexApiClientMockRecorder struct {
	mock *MockCortexApiClient
}

// NewMockCortexApiClient creates a new mock instance.
func NewMockCortexApiClient(ctrl *gomock.Controller) *MockCortexApiClient {
	mock := &MockCortexApiClient{ctrl: ctrl}
	mock.recorder = &MockCortexApiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCortexApiClient) EXPECT() *MockCortexApiClientMockRecorder {
	return m.recorder
}

// Call mocks base method.
func (m *MockCortexApiClient) Call(ctx context.Context, in *axon.CallRequest, opts ...grpc.CallOption) (*axon.CallResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Call", varargs...)
	ret0, _ := ret[0].(*axon.CallResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Call indicates an expected call of Call.
func (mr *MockCortexApiClientMockRecorder) Call(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockCortexApiClient)(nil).Call), varargs...)
}

// MockAxonAgentClient is a mock of AxonAgentClient interface.
type MockAxonAgentClient struct {
	ctrl     *gomock.Controller
	recorder *MockAxonAgentClientMockRecorder
	isgomock struct{}
}

// MockAxonAgentClientMockRecorder is the mock recorder for MockAxonAgentClient.
type MockAxonAgentClientMockRecorder struct {
	mock *MockAxonAgentClient
}

// NewMockAxonAgentClient creates a new mock instance.
func NewMockAxonAgentClient(ctrl *gomock.Controller) *MockAxonAgentClient {
	mock := &MockAxonAgentClient{ctrl: ctrl}
	mock.recorder = &MockAxonAgentClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAxonAgentClient) EXPECT() *MockAxonAgentClientMockRecorder {
	return m.recorder
}

// Dispatch mocks base method.
func (m *MockAxonAgentClient) Dispatch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[axon.DispatchRequest, axon.DispatchMessage], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Dispatch", varargs...)
	ret0, _ := ret[0].(grpc.BidiStreamingClient[axon.DispatchRequest, axon.DispatchMessage])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockAxonAgentClientMockRecorder) Dispatch(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockAxonAgentClient)(nil).Dispatch), varargs...)
}

// GetHandlerHistory mocks base method.
func (m *MockAxonAgentClient) GetHandlerHistory(ctx context.Context, in *axon.GetHandlerHistoryRequest, opts ...grpc.CallOption) (*axon.GetHandlerHistoryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetHandlerHistory", varargs...)
	ret0, _ := ret[0].(*axon.GetHandlerHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHandlerHistory indicates an expected call of GetHandlerHistory.
func (mr *MockAxonAgentClientMockRecorder) GetHandlerHistory(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHandlerHistory", reflect.TypeOf((*MockAxonAgentClient)(nil).GetHandlerHistory), varargs...)
}

// ListHandlers mocks base method.
func (m *MockAxonAgentClient) ListHandlers(ctx context.Context, in *axon.ListHandlersRequest, opts ...grpc.CallOption) (*axon.ListHandlersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListHandlers", varargs...)
	ret0, _ := ret[0].(*axon.ListHandlersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListHandlers indicates an expected call of ListHandlers.
func (mr *MockAxonAgentClientMockRecorder) ListHandlers(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHandlers", reflect.TypeOf((*MockAxonAgentClient)(nil).ListHandlers), varargs...)
}

// RegisterHandler mocks base method.
func (m *MockAxonAgentClient) RegisterHandler(ctx context.Context, in *axon.RegisterHandlerRequest, opts ...grpc.CallOption) (*axon.RegisterHandlerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterHandler", varargs...)
	ret0, _ := ret[0].(*axon.RegisterHandlerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterHandler indicates an expected call of RegisterHandler.
func (mr *MockAxonAgentClientMockRecorder) RegisterHandler(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterHandler", reflect.TypeOf((*MockAxonAgentClient)(nil).RegisterHandler), varargs...)
}

// ReportInvocation mocks base method.
func (m *MockAxonAgentClient) ReportInvocation(ctx context.Context, in *axon.ReportInvocationRequest, opts ...grpc.CallOption) (*axon.ReportInvocationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReportInvocation", varargs...)
	ret0, _ := ret[0].(*axon.ReportInvocationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReportInvocation indicates an expected call of ReportInvocation.
func (mr *MockAxonAgentClientMockRecorder) ReportInvocation(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportInvocation", reflect.TypeOf((*MockAxonAgentClient)(nil).ReportInvocation), varargs...)
}

// UnregisterHandler mocks base method.
func (m *MockAxonAgentClient) UnregisterHandler(ctx context.Context, in *axon.UnregisterHandlerRequest, opts ...grpc.CallOption) (*axon.UnregisterHandlerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnregisterHandler", varargs...)
	ret0, _ := ret[0].(*axon.UnregisterHandlerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnregisterHandler indicates an expected call of UnregisterHandler.
func (mr *MockAxonAgentClientMockRecorder) UnregisterHandler(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterHandler", reflect.TypeOf((*MockAxonAgentClient)(nil).UnregisterHandler), varargs...)
}
