// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: cortex-api.proto

package axon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_cortex_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_cortex_api_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CallRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CallRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_cortex_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_cortex_api_proto_rawDescGZIP(), []int{1}
}

func (x *CallResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CallResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CallResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CallResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_cortex_api_proto protoreflect.FileDescriptor

const file_cortex_api_proto_rawDesc = "" +
	"\n" +
	"\x10cortex-api.proto\x12\vcortex.axon\"p\n" +
	"\vCallRequest\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\"\xd9\x01\n" +
	"\fCallResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12@\n" +
	"\aheaders\x18\x03 \x03(\v2&.cortex.axon.CallResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012H\n" +
	"\tCortexApi\x12;\n" +
	"\x04Call\x12\x18.cortex.axon.CallRequest\x1a\x19.cortex.axon.CallResponseB\x1cZ\x1agithub.com/cortexapps/axonb\x06proto3"

var (
	file_cortex_api_proto_rawDescOnce sync.Once
	file_cortex_api_proto_rawDescData []byte
)

func file_cortex_api_proto_rawDescGZIP() []byte {
	file_cortex_api_proto_rawDescOnce.Do(func() {
		file_cortex_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cortex_api_proto_rawDesc), len(file_cortex_api_proto_rawDesc)))
	})
	return file_cortex_api_proto_rawDescData
}

var file_cortex_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cortex_api_proto_goTypes = []any{
	(*CallRequest)(nil),  // 0: cortex.axon.CallRequest
	(*CallResponse)(nil), // 1: cortex.axon.CallResponse
	nil,                  // 2: cortex.axon.CallResponse.HeadersEntry
}
var file_cortex_api_proto_depIdxs = []int32{
	2, // 0: cortex.axon.CallResponse.headers:type_name -> cortex.axon.CallResponse.HeadersEntry
	0, // 1: cortex.axon.CortexApi.Call:input_type -> cortex.axon.CallRequest
	1, // 2: cortex.axon.CortexApi.Call:output_type -> cortex.axon.CallResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cortex_api_proto_init() }
func file_cortex_api_proto_init() {
	if File_cortex_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cortex_api_proto_rawDesc), len(file_cortex_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cortex_api_proto_goTypes,
		DependencyIndexes: file_cortex_api_proto_depIdxs,
		MessageInfos:      file_cortex_api_proto_msgTypes,
	}.Build()
	File_cortex_api_proto = out.File
	file_cortex_api_proto_goTypes = nil
	file_cortex_api_proto_depIdxs = nil
}
