// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: cortex-api.proto

package axon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CortexApi_Call_FullMethodName = "/cortex.axon.CortexApi/Call"
)

// CortexApiClient is the client API for CortexApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CortexApiClient interface {
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
}

type cortexApiClient struct {
	cc grpc.ClientConnInterface
}

func NewCortexApiClient(cc grpc.ClientConnInterface) CortexApiClient {
	return &cortexApiClient{cc}
}

func (c *cortexApiClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, CortexApi_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CortexApiServer is the server API for CortexApi service.
// All implementations must embed UnimplementedCortexApiServer
// for forward compatibility.
type CortexApiServer interface {
	Call(context.Context, *CallRequest) (*CallResponse, error)
	mustEmbedUnimplementedCortexApiServer()
}

// UnimplementedCortexApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCortexApiServer struct{}

func (UnimplementedCortexApiServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedCortexApiServer) mustEmbedUnimplementedCortexApiServer() {}
func (UnimplementedCortexApiServer) testEmbeddedByValue()                   {}

// UnsafeCortexApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CortexApiServer will
// result in compilation errors.
type UnsafeCortexApiServer interface {
	mustEmbedUnimplementedCortexApiServer()
}

func RegisterCortexApiServer(s grpc.ServiceRegistrar, srv CortexApiServer) {
	// If the following call pancis, it indicates UnimplementedCortexApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CortexApi_ServiceDesc, srv)
}

func _CortexApi_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexApiServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexApi_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexApiServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CortexApi_ServiceDesc is the grpc.ServiceDesc for CortexApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CortexApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cortex.axon.CortexApi",
	HandlerType: (*CortexApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _CortexApi_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cortex-api.proto",
}
