// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: cortex-axon-agent.proto

package axon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandlerInvokeType int32

const (
	HandlerInvokeType_INVOKE        HandlerInvokeType = 0
	HandlerInvokeType_RUN_NOW       HandlerInvokeType = 1
	HandlerInvokeType_CRON_SCHEDULE HandlerInvokeType = 2
	HandlerInvokeType_RUN_INTERVAL  HandlerInvokeType = 3
	HandlerInvokeType_WEBHOOK       HandlerInvokeType = 4
)

// Enum value maps for HandlerInvokeType.
var (
	HandlerInvokeType_name = map[int32]string{
		0: "INVOKE",
		1: "RUN_NOW",
		2: "CRON_SCHEDULE",
		3: "RUN_INTERVAL",
		4: "WEBHOOK",
	}
	HandlerInvokeType_value = map[string]int32{
		"INVOKE":        0,
		"RUN_NOW":       1,
		"CRON_SCHEDULE": 2,
		"RUN_INTERVAL":  3,
		"WEBHOOK":       4,
	}
)

func (x HandlerInvokeType) Enum() *HandlerInvokeType {
	p := new(HandlerInvokeType)
	*p = x
	return p
}

func (x HandlerInvokeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HandlerInvokeType) Descriptor() protoreflect.EnumDescriptor {
	return file_cortex_axon_agent_proto_enumTypes[0].Descriptor()
}

func (HandlerInvokeType) Type() protoreflect.EnumType {
	return &file_cortex_axon_agent_proto_enumTypes[0]
}

func (x HandlerInvokeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HandlerInvokeType.Descriptor instead.
func (HandlerInvokeType) EnumDescriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{0}
}

type DispatchMessageType int32

const (
	DispatchMessageType_DISPATCH_MESSAGE_TYPE_NONE      DispatchMessageType = 0
	DispatchMessageType_DISPATCH_MESSAGE_INVOKE         DispatchMessageType = 1
	DispatchMessageType_DISPATCH_MESSAGE_WORK_COMPLETED DispatchMessageType = 2
)

// Enum value maps for DispatchMessageType.
var (
	DispatchMessageType_name = map[int32]string{
		0: "DISPATCH_MESSAGE_TYPE_NONE",
		1: "DISPATCH_MESSAGE_INVOKE",
		2: "DISPATCH_MESSAGE_WORK_COMPLETED",
	}
	DispatchMessageType_value = map[string]int32{
		"DISPATCH_MESSAGE_TYPE_NONE":      0,
		"DISPATCH_MESSAGE_INVOKE":         1,
		"DISPATCH_MESSAGE_WORK_COMPLETED": 2,
	}
)

func (x DispatchMessageType) Enum() *DispatchMessageType {
	p := new(DispatchMessageType)
	*p = x
	return p
}

func (x DispatchMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DispatchMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_cortex_axon_agent_proto_enumTypes[1].Descriptor()
}

func (DispatchMessageType) Type() protoreflect.EnumType {
	return &file_cortex_axon_agent_proto_enumTypes[1]
}

func (x DispatchMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DispatchMessageType.Descriptor instead.
func (DispatchMessageType) EnumDescriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{1}
}

type RegisterHandlerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DispatchId    string                 `protobuf:"bytes,1,opt,name=dispatch_id,json=dispatchId,proto3" json:"dispatch_id,omitempty"`
	HandlerName   string                 `protobuf:"bytes,2,opt,name=handler_name,json=handlerName,proto3" json:"handler_name,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Options       []*HandlerOption       `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterHandlerRequest) Reset() {
	*x = RegisterHandlerRequest{}
	mi := &file_cortex_axon_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHandlerRequest) ProtoMessage() {}

func (x *RegisterHandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHandlerRequest.ProtoReflect.Descriptor instead.
func (*RegisterHandlerRequest) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterHandlerRequest) GetDispatchId() string {
	if x != nil {
		return x.DispatchId
	}
	return ""
}

func (x *RegisterHandlerRequest) GetHandlerName() string {
	if x != nil {
		return x.HandlerName
	}
	return ""
}

func (x *RegisterHandlerRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *RegisterHandlerRequest) GetOptions() []*HandlerOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type HandlerInvokeOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          HandlerInvokeType      `protobuf:"varint,1,opt,name=type,proto3,enum=cortex.axon.HandlerInvokeType" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlerInvokeOption) Reset() {
	*x = HandlerInvokeOption{}
	mi := &file_cortex_axon_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerInvokeOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerInvokeOption) ProtoMessage() {}

func (x *HandlerInvokeOption) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerInvokeOption.ProtoReflect.Descriptor instead.
func (*HandlerInvokeOption) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{1}
}

func (x *HandlerInvokeOption) GetType() HandlerInvokeType {
	if x != nil {
		return x.Type
	}
	return HandlerInvokeType_INVOKE
}

func (x *HandlerInvokeOption) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type HandlerOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Option:
	//
	//	*HandlerOption_Invoke
	Option        isHandlerOption_Option `protobuf_oneof:"option"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlerOption) Reset() {
	*x = HandlerOption{}
	mi := &file_cortex_axon_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerOption) ProtoMessage() {}

func (x *HandlerOption) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerOption.ProtoReflect.Descriptor instead.
func (*HandlerOption) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HandlerOption) GetOption() isHandlerOption_Option {
	if x != nil {
		return x.Option
	}
	return nil
}

func (x *HandlerOption) GetInvoke() *HandlerInvokeOption {
	if x != nil {
		if x, ok := x.Option.(*HandlerOption_Invoke); ok {
			return x.Invoke
		}
	}
	return nil
}

type isHandlerOption_Option interface {
	isHandlerOption_Option()
}

type HandlerOption_Invoke struct {
	Invoke *HandlerInvokeOption `protobuf:"bytes,1,opt,name=invoke,proto3,oneof"`
}

func (*HandlerOption_Invoke) isHandlerOption_Option() {}

type RegisterHandlerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterHandlerResponse) Reset() {
	*x = RegisterHandlerResponse{}
	mi := &file_cortex_axon_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHandlerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHandlerResponse) ProtoMessage() {}

func (x *RegisterHandlerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHandlerResponse.ProtoReflect.Descriptor instead.
func (*RegisterHandlerResponse) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterHandlerResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RegisterHandlerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnregisterHandlerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterHandlerRequest) Reset() {
	*x = UnregisterHandlerRequest{}
	mi := &file_cortex_axon_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterHandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterHandlerRequest) ProtoMessage() {}

func (x *UnregisterHandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterHandlerRequest.ProtoReflect.Descriptor instead.
func (*UnregisterHandlerRequest) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterHandlerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnregisterHandlerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterHandlerResponse) Reset() {
	*x = UnregisterHandlerResponse{}
	mi := &file_cortex_axon_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterHandlerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterHandlerResponse) ProtoMessage() {}

func (x *UnregisterHandlerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterHandlerResponse.ProtoReflect.Descriptor instead.
func (*UnregisterHandlerResponse) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterHandlerResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListHandlersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHandlersRequest) Reset() {
	*x = ListHandlersRequest{}
	mi := &file_cortex_axon_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHandlersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHandlersRequest) ProtoMessage() {}

func (x *ListHandlersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHandlersRequest.ProtoReflect.Descriptor instead.
func (*ListHandlersRequest) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{6}
}

type HandlerInfo struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Name                       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Options                    []*HandlerOption       `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	DispatchId                 string                 `protobuf:"bytes,20,opt,name=dispatch_id,json=dispatchId,proto3" json:"dispatch_id,omitempty"`
	Id                         string                 `protobuf:"bytes,21,opt,name=id,proto3" json:"id,omitempty"`
	LastInvokedClientTimestamp *timestamppb.Timestamp `protobuf:"bytes,100,opt,name=last_invoked_client_timestamp,json=lastInvokedClientTimestamp,proto3" json:"last_invoked_client_timestamp,omitempty"`
	IsActive                   bool                   `protobuf:"varint,101,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *HandlerInfo) Reset() {
	*x = HandlerInfo{}
	mi := &file_cortex_axon_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerInfo) ProtoMessage() {}

func (x *HandlerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerInfo.ProtoReflect.Descriptor instead.
func (*HandlerInfo) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{7}
}

func (x *HandlerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HandlerInfo) GetOptions() []*HandlerOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *HandlerInfo) GetDispatchId() string {
	if x != nil {
		return x.DispatchId
	}
	return ""
}

func (x *HandlerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HandlerInfo) GetLastInvokedClientTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.LastInvokedClientTimestamp
	}
	return nil
}

func (x *HandlerInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ListHandlersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Handlers      []*HandlerInfo         `protobuf:"bytes,2,rep,name=handlers,proto3" json:"handlers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHandlersResponse) Reset() {
	*x = ListHandlersResponse{}
	mi := &file_cortex_axon_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHandlersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHandlersResponse) ProtoMessage() {}

func (x *ListHandlersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHandlersResponse.ProtoReflect.Descriptor instead.
func (*ListHandlersResponse) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ListHandlersResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ListHandlersResponse) GetHandlers() []*HandlerInfo {
	if x != nil {
		return x.Handlers
	}
	return nil
}

type DispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DispatchId    string                 `protobuf:"bytes,1,opt,name=dispatch_id,json=dispatchId,proto3" json:"dispatch_id,omitempty"`
	ClientVersion string                 `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_cortex_axon_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{9}
}

func (x *DispatchRequest) GetDispatchId() string {
	if x != nil {
		return x.DispatchId
	}
	return ""
}

func (x *DispatchRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type DispatchMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  DispatchMessageType    `protobuf:"varint,1,opt,name=type,proto3,enum=cortex.axon.DispatchMessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*DispatchMessage_Invoke
	Message       isDispatchMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchMessage) Reset() {
	*x = DispatchMessage{}
	mi := &file_cortex_axon_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchMessage) ProtoMessage() {}

func (x *DispatchMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchMessage.ProtoReflect.Descriptor instead.
func (*DispatchMessage) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{10}
}

func (x *DispatchMessage) GetType() DispatchMessageType {
	if x != nil {
		return x.Type
	}
	return DispatchMessageType_DISPATCH_MESSAGE_TYPE_NONE
}

func (x *DispatchMessage) GetMessage() isDispatchMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *DispatchMessage) GetInvoke() *DispatchHandlerInvoke {
	if x != nil {
		if x, ok := x.Message.(*DispatchMessage_Invoke); ok {
			return x.Invoke
		}
	}
	return nil
}

type isDispatchMessage_Message interface {
	isDispatchMessage_Message()
}

type DispatchMessage_Invoke struct {
	Invoke *DispatchHandlerInvoke `protobuf:"bytes,10,opt,name=invoke,proto3,oneof"`
}

func (*DispatchMessage_Invoke) isDispatchMessage_Message() {}

type DispatchHandlerInvoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvocationId  string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	DispatchId    string                 `protobuf:"bytes,2,opt,name=dispatch_id,json=dispatchId,proto3" json:"dispatch_id,omitempty"`
	HandlerId     string                 `protobuf:"bytes,3,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	HandlerName   string                 `protobuf:"bytes,4,opt,name=handler_name,json=handlerName,proto3" json:"handler_name,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,10,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Reason        HandlerInvokeType      `protobuf:"varint,11,opt,name=reason,proto3,enum=cortex.axon.HandlerInvokeType" json:"reason,omitempty"`
	Args          map[string]string      `protobuf:"bytes,20,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchHandlerInvoke) Reset() {
	*x = DispatchHandlerInvoke{}
	mi := &file_cortex_axon_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchHandlerInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchHandlerInvoke) ProtoMessage() {}

func (x *DispatchHandlerInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchHandlerInvoke.ProtoReflect.Descriptor instead.
func (*DispatchHandlerInvoke) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{11}
}

func (x *DispatchHandlerInvoke) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *DispatchHandlerInvoke) GetDispatchId() string {
	if x != nil {
		return x.DispatchId
	}
	return ""
}

func (x *DispatchHandlerInvoke) GetHandlerId() string {
	if x != nil {
		return x.HandlerId
	}
	return ""
}

func (x *DispatchHandlerInvoke) GetHandlerName() string {
	if x != nil {
		return x.HandlerName
	}
	return ""
}

func (x *DispatchHandlerInvoke) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *DispatchHandlerInvoke) GetReason() HandlerInvokeType {
	if x != nil {
		return x.Reason
	}
	return HandlerInvokeType_INVOKE
}

func (x *DispatchHandlerInvoke) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_cortex_axon_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{12}
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReportInvocationRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	HandlerInvoke        *DispatchHandlerInvoke `protobuf:"bytes,1,opt,name=handler_invoke,json=handlerInvoke,proto3" json:"handler_invoke,omitempty"`
	StartClientTimestamp *timestamppb.Timestamp `protobuf:"bytes,100,opt,name=start_client_timestamp,json=startClientTimestamp,proto3" json:"start_client_timestamp,omitempty"`
	DurationMs           int32                  `protobuf:"varint,101,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*ReportInvocationRequest_Result
	//	*ReportInvocationRequest_Error
	Message       isReportInvocationRequest_Message `protobuf_oneof:"message"`
	Logs          []*Log                            `protobuf:"bytes,300,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportInvocationRequest) Reset() {
	*x = ReportInvocationRequest{}
	mi := &file_cortex_axon_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInvocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInvocationRequest) ProtoMessage() {}

func (x *ReportInvocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInvocationRequest.ProtoReflect.Descriptor instead.
func (*ReportInvocationRequest) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ReportInvocationRequest) GetHandlerInvoke() *DispatchHandlerInvoke {
	if x != nil {
		return x.HandlerInvoke
	}
	return nil
}

func (x *ReportInvocationRequest) GetStartClientTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.StartClientTimestamp
	}
	return nil
}

func (x *ReportInvocationRequest) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ReportInvocationRequest) GetMessage() isReportInvocationRequest_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ReportInvocationRequest) GetResult() *InvokeResult {
	if x != nil {
		if x, ok := x.Message.(*ReportInvocationRequest_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ReportInvocationRequest) GetError() *Error {
	if x != nil {
		if x, ok := x.Message.(*ReportInvocationRequest_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ReportInvocationRequest) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

type isReportInvocationRequest_Message interface {
	isReportInvocationRequest_Message()
}

type ReportInvocationRequest_Result struct {
	Result *InvokeResult `protobuf:"bytes,200,opt,name=result,proto3,oneof"`
}

type ReportInvocationRequest_Error struct {
	Error *Error `protobuf:"bytes,201,opt,name=error,proto3,oneof"`
}

func (*ReportInvocationRequest_Result) isReportInvocationRequest_Message() {}

func (*ReportInvocationRequest_Error) isReportInvocationRequest_Message() {}

type ReportInvocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportInvocationResponse) Reset() {
	*x = ReportInvocationResponse{}
	mi := &file_cortex_axon_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInvocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInvocationResponse) ProtoMessage() {}

func (x *ReportInvocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInvocationResponse.ProtoReflect.Descriptor instead.
func (*ReportInvocationResponse) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ReportInvocationResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type InvokeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,10,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResult) Reset() {
	*x = InvokeResult{}
	mi := &file_cortex_axon_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResult) ProtoMessage() {}

func (x *InvokeResult) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResult.ProtoReflect.Descriptor instead.
func (*InvokeResult) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{15}
}

func (x *InvokeResult) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetHandlerHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandlerName   string                 `protobuf:"bytes,1,opt,name=handler_name,json=handlerName,proto3" json:"handler_name,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IncludeLogs   bool                   `protobuf:"varint,4,opt,name=include_logs,json=includeLogs,proto3" json:"include_logs,omitempty"`
	Tail          int32                  `protobuf:"varint,5,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHandlerHistoryRequest) Reset() {
	*x = GetHandlerHistoryRequest{}
	mi := &file_cortex_axon_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHandlerHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHandlerHistoryRequest) ProtoMessage() {}

func (x *GetHandlerHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHandlerHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHandlerHistoryRequest) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{16}
}

func (x *GetHandlerHistoryRequest) GetHandlerName() string {
	if x != nil {
		return x.HandlerName
	}
	return ""
}

func (x *GetHandlerHistoryRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetHandlerHistoryRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetHandlerHistoryRequest) GetIncludeLogs() bool {
	if x != nil {
		return x.IncludeLogs
	}
	return false
}

func (x *GetHandlerHistoryRequest) GetTail() int32 {
	if x != nil {
		return x.Tail
	}
	return 0
}

type HandlerExecution struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	HandlerName            string                 `protobuf:"bytes,1,opt,name=handler_name,json=handlerName,proto3" json:"handler_name,omitempty"`
	HandlerId              string                 `protobuf:"bytes,2,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	InvocationId           string                 `protobuf:"bytes,3,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	DispatchId             string                 `protobuf:"bytes,4,opt,name=dispatch_id,json=dispatchId,proto3" json:"dispatch_id,omitempty"`
	PublishServerTimestamp *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=publish_server_timestamp,json=publishServerTimestamp,proto3" json:"publish_server_timestamp,omitempty"`
	ReceiveServerTimestamp *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=receive_server_timestamp,json=receiveServerTimestamp,proto3" json:"receive_server_timestamp,omitempty"`
	StartClientTimestamp   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=start_client_timestamp,json=startClientTimestamp,proto3" json:"start_client_timestamp,omitempty"`
	DurationMs             int32                  `protobuf:"varint,13,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Error                  *Error                 `protobuf:"bytes,20,opt,name=error,proto3" json:"error,omitempty"`
	Logs                   []*Log                 `protobuf:"bytes,30,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HandlerExecution) Reset() {
	*x = HandlerExecution{}
	mi := &file_cortex_axon_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerExecution) ProtoMessage() {}

func (x *HandlerExecution) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerExecution.ProtoReflect.Descriptor instead.
func (*HandlerExecution) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{17}
}

func (x *HandlerExecution) GetHandlerName() string {
	if x != nil {
		return x.HandlerName
	}
	return ""
}

func (x *HandlerExecution) GetHandlerId() string {
	if x != nil {
		return x.HandlerId
	}
	return ""
}

func (x *HandlerExecution) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *HandlerExecution) GetDispatchId() string {
	if x != nil {
		return x.DispatchId
	}
	return ""
}

func (x *HandlerExecution) GetPublishServerTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishServerTimestamp
	}
	return nil
}

func (x *HandlerExecution) GetReceiveServerTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceiveServerTimestamp
	}
	return nil
}

func (x *HandlerExecution) GetStartClientTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.StartClientTimestamp
	}
	return nil
}

func (x *HandlerExecution) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *HandlerExecution) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *HandlerExecution) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

type GetHandlerHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	History       []*HandlerExecution    `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHandlerHistoryResponse) Reset() {
	*x = GetHandlerHistoryResponse{}
	mi := &file_cortex_axon_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHandlerHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHandlerHistoryResponse) ProtoMessage() {}

func (x *GetHandlerHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_axon_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHandlerHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHandlerHistoryResponse) Descriptor() ([]byte, []int) {
	return file_cortex_axon_agent_proto_rawDescGZIP(), []int{18}
}

func (x *GetHandlerHistoryResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetHandlerHistoryResponse) GetHistory() []*HandlerExecution {
	if x != nil {
		return x.History
	}
	return nil
}

var File_cortex_axon_agent_proto protoreflect.FileDescriptor

const file_cortex_axon_agent_proto_rawDesc = "" +
	"\n" +
	"\x17cortex-axon-agent.proto\x12\vcortex.axon\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x01\n" +
	"\x16RegisterHandlerRequest\x12\x1f\n" +
	"\vdispatch_id\x18\x01 \x01(\tR\n" +
	"dispatchId\x12!\n" +
	"\fhandler_name\x18\x02 \x01(\tR\vhandlerName\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\x124\n" +
	"\aoptions\x18\x04 \x03(\v2\x1a.cortex.axon.HandlerOptionR\aoptions\"_\n" +
	"\x13HandlerInvokeOption\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.cortex.axon.HandlerInvokeTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"U\n" +
	"\rHandlerOption\x12:\n" +
	"\x06invoke\x18\x01 \x01(\v2 .cortex.axon.HandlerInvokeOptionH\x00R\x06invokeB\b\n" +
	"\x06option\"S\n" +
	"\x17RegisterHandlerResponse\x12(\n" +
	"\x05error\x18\x01 \x01(\v2\x12.cortex.axon.ErrorR\x05error\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"*\n" +
	"\x18UnregisterHandlerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x19UnregisterHandlerResponse\x12(\n" +
	"\x05error\x18\x01 \x01(\v2\x12.cortex.axon.ErrorR\x05error\"\x15\n" +
	"\x13ListHandlersRequest\"\x84\x02\n" +
	"\vHandlerInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\aoptions\x18\x02 \x03(\v2\x1a.cortex.axon.HandlerOptionR\aoptions\x12\x1f\n" +
	"\vdispatch_id\x18\x14 \x01(\tR\n" +
	"dispatchId\x12\x0e\n" +
	"\x02id\x18\x15 \x01(\tR\x02id\x12]\n" +
	"\x1dlast_invoked_client_timestamp\x18d \x01(\v2\x1a.google.protobuf.TimestampR\x1alastInvokedClientTimestamp\x12\x1b\n" +
	"\tis_active\x18e \x01(\bR\bisActive\"v\n" +
	"\x14ListHandlersResponse\x12(\n" +
	"\x05error\x18\x01 \x01(\v2\x12.cortex.axon.ErrorR\x05error\x124\n" +
	"\bhandlers\x18\x02 \x03(\v2\x18.cortex.axon.HandlerInfoR\bhandlers\"Y\n" +
	"\x0fDispatchRequest\x12\x1f\n" +
	"\vdispatch_id\x18\x01 \x01(\tR\n" +
	"dispatchId\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\"\x90\x01\n" +
	"\x0fDispatchMessage\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .cortex.axon.DispatchMessageTypeR\x04type\x12<\n" +
	"\x06invoke\x18\n" +
	" \x01(\v2\".cortex.axon.DispatchHandlerInvokeH\x00R\x06invokeB\t\n" +
	"\amessage\"\xf1\x02\n" +
	"\x15DispatchHandlerInvoke\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12\x1f\n" +
	"\vdispatch_id\x18\x02 \x01(\tR\n" +
	"dispatchId\x12\x1d\n" +
	"\n" +
	"handler_id\x18\x03 \x01(\tR\thandlerId\x12!\n" +
	"\fhandler_name\x18\x04 \x01(\tR\vhandlerName\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\n" +
	" \x01(\x05R\ttimeoutMs\x126\n" +
	"\x06reason\x18\v \x01(\x0e2\x1e.cortex.axon.HandlerInvokeTypeR\x06reason\x12@\n" +
	"\x04args\x18\x14 \x03(\v2,.cortex.axon.DispatchHandlerInvoke.ArgsEntryR\x04args\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\x03Log\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xec\x02\n" +
	"\x17ReportInvocationRequest\x12I\n" +
	"\x0ehandler_invoke\x18\x01 \x01(\v2\".cortex.axon.DispatchHandlerInvokeR\rhandlerInvoke\x12P\n" +
	"\x16start_client_timestamp\x18d \x01(\v2\x1a.google.protobuf.TimestampR\x14startClientTimestamp\x12\x1f\n" +
	"\vduration_ms\x18e \x01(\x05R\n" +
	"durationMs\x124\n" +
	"\x06result\x18\xc8\x01 \x01(\v2\x19.cortex.axon.InvokeResultH\x00R\x06result\x12+\n" +
	"\x05error\x18\xc9\x01 \x01(\v2\x12.cortex.axon.ErrorH\x00R\x05error\x12%\n" +
	"\x04logs\x18\xac\x02 \x03(\v2\x10.cortex.axon.LogR\x04logsB\t\n" +
	"\amessage\"D\n" +
	"\x18ReportInvocationResponse\x12(\n" +
	"\x05error\x18\x01 \x01(\v2\x12.cortex.axon.ErrorR\x05error\"$\n" +
	"\fInvokeResult\x12\x14\n" +
	"\x05value\x18\n" +
	" \x01(\tR\x05value\"\xe6\x01\n" +
	"\x18GetHandlerHistoryRequest\x12!\n" +
	"\fhandler_name\x18\x01 \x01(\tR\vhandlerName\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12!\n" +
	"\finclude_logs\x18\x04 \x01(\bR\vincludeLogs\x12\x12\n" +
	"\x04tail\x18\x05 \x01(\x05R\x04tail\"\x89\x04\n" +
	"\x10HandlerExecution\x12!\n" +
	"\fhandler_name\x18\x01 \x01(\tR\vhandlerName\x12\x1d\n" +
	"\n" +
	"handler_id\x18\x02 \x01(\tR\thandlerId\x12#\n" +
	"\rinvocation_id\x18\x03 \x01(\tR\finvocationId\x12\x1f\n" +
	"\vdispatch_id\x18\x04 \x01(\tR\n" +
	"dispatchId\x12T\n" +
	"\x18publish_server_timestamp\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x16publishServerTimestamp\x12T\n" +
	"\x18receive_server_timestamp\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x16receiveServerTimestamp\x12P\n" +
	"\x16start_client_timestamp\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x14startClientTimestamp\x12\x1f\n" +
	"\vduration_ms\x18\r \x01(\x05R\n" +
	"durationMs\x12(\n" +
	"\x05error\x18\x14 \x01(\v2\x12.cortex.axon.ErrorR\x05error\x12$\n" +
	"\x04logs\x18\x1e \x03(\v2\x10.cortex.axon.LogR\x04logs\"~\n" +
	"\x19GetHandlerHistoryResponse\x12(\n" +
	"\x05error\x18\x01 \x01(\v2\x12.cortex.axon.ErrorR\x05error\x127\n" +
	"\ahistory\x18\x02 \x03(\v2\x1d.cortex.axon.HandlerExecutionR\ahistory*^\n" +
	"\x11HandlerInvokeType\x12\n" +
	"\n" +
	"\x06INVOKE\x10\x00\x12\v\n" +
	"\aRUN_NOW\x10\x01\x12\x11\n" +
	"\rCRON_SCHEDULE\x10\x02\x12\x10\n" +
	"\fRUN_INTERVAL\x10\x03\x12\v\n" +
	"\aWEBHOOK\x10\x04*w\n" +
	"\x13DispatchMessageType\x12\x1e\n" +
	"\x1aDISPATCH_MESSAGE_TYPE_NONE\x10\x00\x12\x1b\n" +
	"\x17DISPATCH_MESSAGE_INVOKE\x10\x01\x12#\n" +
	"\x1fDISPATCH_MESSAGE_WORK_COMPLETED\x10\x022\xb3\x04\n" +
	"\tAxonAgent\x12\\\n" +
	"\x0fRegisterHandler\x12#.cortex.axon.RegisterHandlerRequest\x1a$.cortex.axon.RegisterHandlerResponse\x12b\n" +
	"\x11UnregisterHandler\x12%.cortex.axon.UnregisterHandlerRequest\x1a&.cortex.axon.UnregisterHandlerResponse\x12S\n" +
	"\fListHandlers\x12 .cortex.axon.ListHandlersRequest\x1a!.cortex.axon.ListHandlersResponse\x12b\n" +
	"\x11GetHandlerHistory\x12%.cortex.axon.GetHandlerHistoryRequest\x1a&.cortex.axon.GetHandlerHistoryResponse\x12J\n" +
	"\bDispatch\x12\x1c.cortex.axon.DispatchRequest\x1a\x1c.cortex.axon.DispatchMessage(\x010\x01\x12_\n" +
	"\x10ReportInvocation\x12$.cortex.axon.ReportInvocationRequest\x1a%.cortex.axon.ReportInvocationResponseB\x1cZ\x1agithub.com/cortexapps/axonb\x06proto3"

var (
	file_cortex_axon_agent_proto_rawDescOnce sync.Once
	file_cortex_axon_agent_proto_rawDescData []byte
)

func file_cortex_axon_agent_proto_rawDescGZIP() []byte {
	file_cortex_axon_agent_proto_rawDescOnce.Do(func() {
		file_cortex_axon_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cortex_axon_agent_proto_rawDesc), len(file_cortex_axon_agent_proto_rawDesc)))
	})
	return file_cortex_axon_agent_proto_rawDescData
}

var file_cortex_axon_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cortex_axon_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_cortex_axon_agent_proto_goTypes = []any{
	(HandlerInvokeType)(0),            // 0: cortex.axon.HandlerInvokeType
	(DispatchMessageType)(0),          // 1: cortex.axon.DispatchMessageType
	(*RegisterHandlerRequest)(nil),    // 2: cortex.axon.RegisterHandlerRequest
	(*HandlerInvokeOption)(nil),       // 3: cortex.axon.HandlerInvokeOption
	(*HandlerOption)(nil),             // 4: cortex.axon.HandlerOption
	(*RegisterHandlerResponse)(nil),   // 5: cortex.axon.RegisterHandlerResponse
	(*UnregisterHandlerRequest)(nil),  // 6: cortex.axon.UnregisterHandlerRequest
	(*UnregisterHandlerResponse)(nil), // 7: cortex.axon.UnregisterHandlerResponse
	(*ListHandlersRequest)(nil),       // 8: cortex.axon.ListHandlersRequest
	(*HandlerInfo)(nil),               // 9: cortex.axon.HandlerInfo
	(*ListHandlersResponse)(nil),      // 10: cortex.axon.ListHandlersResponse
	(*DispatchRequest)(nil),           // 11: cortex.axon.DispatchRequest
	(*DispatchMessage)(nil),           // 12: cortex.axon.DispatchMessage
	(*DispatchHandlerInvoke)(nil),     // 13: cortex.axon.DispatchHandlerInvoke
	(*Log)(nil),                       // 14: cortex.axon.Log
	(*ReportInvocationRequest)(nil),   // 15: cortex.axon.ReportInvocationRequest
	(*ReportInvocationResponse)(nil),  // 16: cortex.axon.ReportInvocationResponse
	(*InvokeResult)(nil),              // 17: cortex.axon.InvokeResult
	(*GetHandlerHistoryRequest)(nil),  // 18: cortex.axon.GetHandlerHistoryRequest
	(*HandlerExecution)(nil),          // 19: cortex.axon.HandlerExecution
	(*GetHandlerHistoryResponse)(nil), // 20: cortex.axon.GetHandlerHistoryResponse
	nil,                               // 21: cortex.axon.DispatchHandlerInvoke.ArgsEntry
	(*Error)(nil),                     // 22: cortex.axon.Error
	(*timestamppb.Timestamp)(nil),     // 23: google.protobuf.Timestamp
}
var file_cortex_axon_agent_proto_depIdxs = []int32{
	4,  // 0: cortex.axon.RegisterHandlerRequest.options:type_name -> cortex.axon.HandlerOption
	0,  // 1: cortex.axon.HandlerInvokeOption.type:type_name -> cortex.axon.HandlerInvokeType
	3,  // 2: cortex.axon.HandlerOption.invoke:type_name -> cortex.axon.HandlerInvokeOption
	22, // 3: cortex.axon.RegisterHandlerResponse.error:type_name -> cortex.axon.Error
	22, // 4: cortex.axon.UnregisterHandlerResponse.error:type_name -> cortex.axon.Error
	4,  // 5: cortex.axon.HandlerInfo.options:type_name -> cortex.axon.HandlerOption
	23, // 6: cortex.axon.HandlerInfo.last_invoked_client_timestamp:type_name -> google.protobuf.Timestamp
	22, // 7: cortex.axon.ListHandlersResponse.error:type_name -> cortex.axon.Error
	9,  // 8: cortex.axon.ListHandlersResponse.handlers:type_name -> cortex.axon.HandlerInfo
	1,  // 9: cortex.axon.DispatchMessage.type:type_name -> cortex.axon.DispatchMessageType
	13, // 10: cortex.axon.DispatchMessage.invoke:type_name -> cortex.axon.DispatchHandlerInvoke
	0,  // 11: cortex.axon.DispatchHandlerInvoke.reason:type_name -> cortex.axon.HandlerInvokeType
	21, // 12: cortex.axon.DispatchHandlerInvoke.args:type_name -> cortex.axon.DispatchHandlerInvoke.ArgsEntry
	23, // 13: cortex.axon.Log.timestamp:type_name -> google.protobuf.Timestamp
	13, // 14: cortex.axon.ReportInvocationRequest.handler_invoke:type_name -> cortex.axon.DispatchHandlerInvoke
	23, // 15: cortex.axon.ReportInvocationRequest.start_client_timestamp:type_name -> google.protobuf.Timestamp
	17, // 16: cortex.axon.ReportInvocationRequest.result:type_name -> cortex.axon.InvokeResult
	22, // 17: cortex.axon.ReportInvocationRequest.error:type_name -> cortex.axon.Error
	14, // 18: cortex.axon.ReportInvocationRequest.logs:type_name -> cortex.axon.Log
	22, // 19: cortex.axon.ReportInvocationResponse.error:type_name -> cortex.axon.Error
	23, // 20: cortex.axon.GetHandlerHistoryRequest.start_time:type_name -> google.protobuf.Timestamp
	23, // 21: cortex.axon.GetHandlerHistoryRequest.end_time:type_name -> google.protobuf.Timestamp
	23, // 22: cortex.axon.HandlerExecution.publish_server_timestamp:type_name -> google.protobuf.Timestamp
	23, // 23: cortex.axon.HandlerExecution.receive_server_timestamp:type_name -> google.protobuf.Timestamp
	23, // 24: cortex.axon.HandlerExecution.start_client_timestamp:type_name -> google.protobuf.Timestamp
	22, // 25: cortex.axon.HandlerExecution.error:type_name -> cortex.axon.Error
	14, // 26: cortex.axon.HandlerExecution.logs:type_name -> cortex.axon.Log
	22, // 27: cortex.axon.GetHandlerHistoryResponse.error:type_name -> cortex.axon.Error
	19, // 28: cortex.axon.GetHandlerHistoryResponse.history:type_name -> cortex.axon.HandlerExecution
	2,  // 29: cortex.axon.AxonAgent.RegisterHandler:input_type -> cortex.axon.RegisterHandlerRequest
	6,  // 30: cortex.axon.AxonAgent.UnregisterHandler:input_type -> cortex.axon.UnregisterHandlerRequest
	8,  // 31: cortex.axon.AxonAgent.ListHandlers:input_type -> cortex.axon.ListHandlersRequest
	18, // 32: cortex.axon.AxonAgent.GetHandlerHistory:input_type -> cortex.axon.GetHandlerHistoryRequest
	11, // 33: cortex.axon.AxonAgent.Dispatch:input_type -> cortex.axon.DispatchRequest
	15, // 34: cortex.axon.AxonAgent.ReportInvocation:input_type -> cortex.axon.ReportInvocationRequest
	5,  // 35: cortex.axon.AxonAgent.RegisterHandler:output_type -> cortex.axon.RegisterHandlerResponse
	7,  // 36: cortex.axon.AxonAgent.UnregisterHandler:output_type -> cortex.axon.UnregisterHandlerResponse
	10, // 37: cortex.axon.AxonAgent.ListHandlers:output_type -> cortex.axon.ListHandlersResponse
	20, // 38: cortex.axon.AxonAgent.GetHandlerHistory:output_type -> cortex.axon.GetHandlerHistoryResponse
	12, // 39: cortex.axon.AxonAgent.Dispatch:output_type -> cortex.axon.DispatchMessage
	16, // 40: cortex.axon.AxonAgent.ReportInvocation:output_type -> cortex.axon.ReportInvocationResponse
	35, // [35:41] is the sub-list for method output_type
	29, // [29:35] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_cortex_axon_agent_proto_init() }
func file_cortex_axon_agent_proto_init() {
	if File_cortex_axon_agent_proto != nil {
		return
	}
	file_common_proto_init()
	file_cortex_axon_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*HandlerOption_Invoke)(nil),
	}
	file_cortex_axon_agent_proto_msgTypes[10].OneofWrappers = []any{
		(*DispatchMessage_Invoke)(nil),
	}
	file_cortex_axon_agent_proto_msgTypes[13].OneofWrappers = []any{
		(*ReportInvocationRequest_Result)(nil),
		(*ReportInvocationRequest_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cortex_axon_agent_proto_rawDesc), len(file_cortex_axon_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cortex_axon_agent_proto_goTypes,
		DependencyIndexes: file_cortex_axon_agent_proto_depIdxs,
		EnumInfos:         file_cortex_axon_agent_proto_enumTypes,
		MessageInfos:      file_cortex_axon_agent_proto_msgTypes,
	}.Build()
	File_cortex_axon_agent_proto = out.File
	file_cortex_axon_agent_proto_goTypes = nil
	file_cortex_axon_agent_proto_depIdxs = nil
}
